server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create